#######################
# Workflow Definitions
#######################
workflows:
  version: 2
  test-deploy:
    jobs:
    - test

#######################
# Job Definitions
#######################
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10.15.1-browsers
    working_directory: ~/ci-cd-101-workshop

    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: yarn
      - run: 
          name: Run Test Suite
          command: yarn test

